# Exercise 1: Introduction to Data Analysis

## 1. What Is Data Analysis?

Data analysis is the process of collecting, organising, examining, and interpreting data to find useful information. It helps people understand what happened, identify patterns, and make better decisions based on facts rather than guesses.

For example, as a PUBG tournament organiser, I can analyse match results, player rankings, kills, team performance, and tournament registrations to understand how well an event performed.

## 2. Why Is Data Analysis Important in Modern Contexts?

Data analysis is important because organisations generate large amounts of data every day. By analysing this information, they can identify problems, improve performance, understand people's behaviour, and make better decisions.

In esports, data analysis helps tournament organisers evaluate player performance, improve tournament formats, understand audience engagement, and attract sponsors. For example, by analysing YouTube views, Discord activity, and tournament participation, an organiser can understand which events attract the most interest.

Today, data analysis is also increasingly used with artificial intelligence and machine learning to identify patterns and predict possible outcomes. However, the quality of the data is important because incorrect or incomplete data can lead to poor decisions.

## 3. Three Areas Where Data Analysis Is Applied Today

### A. Esports and Gaming

Data analysis is used to evaluate players, teams, tournaments, and audience engagement. Organisers can examine kills, match placements, win rates, registrations, and viewership statistics.

For example, a PUBG tournament organiser can analyse match results to create accurate rankings, identify top-performing teams, and understand which tournaments attract more viewers. This information can also help when presenting performance reports to sponsors.

### B. Healthcare

Hospitals and healthcare organisations analyse patient information, medical test results, and treatment outcomes. This helps healthcare professionals identify trends, plan resources, and support better decisions about patient care.

For example, hospitals can analyse patient admission data to estimate how many beds and medical staff may be needed during busy periods.

### C. Banking and Finance

Banks and financial institutions use data analysis to understand spending patterns, assess credit applications, and detect potentially fraudulent transactions.

For example, a bank can analyse a customer's financial information to help assess whether the customer meets the requirements for a credit card. It can also identify unusual transaction patterns that may indicate fraud.

## Conclusion

Data analysis is an important skill in the modern world because it turns raw data into useful information. It helps people make informed decisions, solve problems, and improve performance. From organising PUBG tournaments to managing hospitals and preventing financial fraud, data analysis plays an important role in many industries.

In [1]:
!unzip "How Much Sleep Do Americans"

Archive:  How Much Sleep Do Americans.zip
  inflating: How Much Sleep Do Americans/Time Americans Spend Sleeping.csv

In [3]:
import pandas as pd
sleep_df = pd.read_csv("/content/How Much Sleep Do Americans.zip")

sleep_df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [8]:
!unzip "Global Trends in Mental Health Disorder"
mental_health_df = pd.read_csv("/content/Global Trends in Mental Health Disorder.zip")

mental_health_df.head()

Archive:  Global Trends in Mental Health Disorder.zip
replace Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

/tmp/ipykernel_1122/2033217009.py:2: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  mental_health_df = pd.read_csv("/content/Global Trends in Mental Health Disorder.zip")

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [16]:
!unzip "Credit Card Approvals (Clean Data)"
credit_card_df = pd.read_csv("/content/Credit Card Approvals (Clean Data)/clean_dataset.csv")

credit_card_df.head()

Archive:  Credit Card Approvals (Clean Data).zip
replace Credit Card Approvals (Clean Data)/clean_dataset.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [17]:
credit_card_df = pd.read_csv(
    "/content/Credit Card Approvals (Clean Data)/clean_dataset.csv"
)

credit_card_df.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [18]:
# Displaying all three datasets

print("Sleep Dataset")
display(sleep_df.head())

print("Mental Health Dataset")
display(mental_health_df.head())

print("Credit Card Dataset")
display(credit_card_df.head())

Sleep Dataset

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

Mental Health Dataset

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

Credit Card Dataset

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

## Exercise 2: Dataset Descriptions

### 1. How Much Sleep Do Americans Really Get?
This dataset contains information about the time Americans spend sleeping. It can be used to explore sleep patterns across different years and population groups.

### 2. Global Trends in Mental Health Disorder
This dataset contains information about mental health disorders across countries and years. It can be used to explore trends and differences in reported disorder measures.

### 3. Credit Card Approvals
This dataset contains information about credit card applicants and approval-related data. It can be used to explore applicant characteristics and patterns in credit card approval decisions.

In [19]:
print("Sleep Dataset")
print(sleep_df.shape)
print(sleep_df.info())

print("Mental Health Dataset")
print(mental_health_df.shape)
print(mental_health_df.info())

print("Credit Card Dataset")
print(credit_card_df.shape)
print(credit_card_df.info())

Sleep Dataset
(945, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    object
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    object
 6   Age Group                 945 non-null    object
 7   Activity                  945 non-null    object
 8   Sex                       945 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 66.6+ KB
None
Mental Health Dataset
(108553, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108553 entries, 0 to 108552
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   index                      108553 non-null  int64
 1   Entity                     108553 non-null  object
 2   Code                       103141 non-null  object
 3   Year                       108553 non-null  object
 4   Schizophrenia (%)          25875 non-null   object
 5   Bipolar disorder (%)       19406 non-null   object
 6   Eating disorders (%)       100236 non-null  object
 7   Anxiety disorders (%)      6468 non-null    float64
 8   Drug use disorders (%)     6468 non-null    float64
 9   Depression (%)             6468 non-null    float64
 10  Alcohol use disorders (%)  6468 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 9.1+ MB
None
Credit Card Dataset
(690, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          690 non-null    int64
 1   Age             690 non-null    float64
 2   Debt            690 non-null    float64
 3   Married         690 non-null    int64
 4   BankCustomer    690 non-null    int64
 5   Industry        690 non-null    object
 6   Ethnicity       690 non-null    object
 7   YearsEmployed   690 non-null    float64
 8   PriorDefault    690 non-null    int64
 9   Employed        690 non-null    int64
 10  CreditScore     690 non-null    int64
 11  DriversLicense  690 non-null    int64
 12  Citizen         690 non-null    object
 13  ZipCode         690 non-null    int64
 14  Income          690 non-null    int64
 15  Approved        690 non-null    int64
dtypes: float64(3), int64(10), object(3)
memory usage: 86.4+ KB
None

Exercise 3: Identifying Data Types


Objective: Learn to identify different data types.
Task:
For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.

In [20]:
print("Sleep Dataset")
print(sleep_df.columns.tolist())

print("Mental Health Dataset")
print(mental_health_df.columns.tolist())

print("Credit Card Dataset")
print(credit_card_df.columns.tolist())

Sleep Dataset
['index', 'Year', 'Period', 'Avg hrs per day sleeping', 'Standard Error', 'Type of Days', 'Age Group', 'Activity', 'Sex']
Mental Health Dataset
['index', 'Entity', 'Code', 'Year', 'Schizophrenia (%)', 'Bipolar disorder (%)', 'Eating disorders (%)', 'Anxiety disorders (%)', 'Drug use disorders (%)', 'Depression (%)', 'Alcohol use disorders (%)']
Credit Card Dataset
['Gender', 'Age', 'Debt', 'Married', 'BankCustomer', 'Industry', 'Ethnicity', 'YearsEmployed', 'PriorDefault', 'Employed', 'CreditScore', 'DriversLicense', 'Citizen', 'ZipCode', 'Income', 'Approved']

In [21]:
for name, df in [
    ("Sleep Dataset", sleep_df),
    ("Mental Health Dataset", mental_health_df),
    ("Credit Card Dataset", credit_card_df)
]:
  print(f"\n{name}")
  for column in df.columns:
    print("_", column)

Sleep Dataset
_ index
_ Year
_ Period
_ Avg hrs per day sleeping
_ Standard Error
_ Type of Days
_ Age Group
_ Activity
_ Sex

Mental Health Dataset
_ index
_ Entity
_ Code
_ Year
_ Schizophrenia (%)
_ Bipolar disorder (%)
_ Eating disorders (%)
_ Anxiety disorders (%)
_ Drug use disorders (%)
_ Depression (%)
_ Alcohol use disorders (%)

Credit Card Dataset
_ Gender
_ Age
_ Debt
_ Married
_ BankCustomer
_ Industry
_ Ethnicity
_ YearsEmployed
_ PriorDefault
_ Employed
_ CreditScore
_ DriversLicense
_ Citizen
_ ZipCode
_ Income
_ Approved